AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation for content ingest deploy
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/lambda-role
      Code:
        S3Bucket: my-bucket
        S3Key: function.zip
      Runtime: python38
      Timeout: 5
      TracingConfig:
        Mode: Active
